### ISSUE TITLE
nova_client找不到security_group

### ISSUE THREAD

**Issue by heng-Yuan** [WinstonZheng/PersonalNotes#2]
你好，我按照官网文档安装newton版本的dashboard也出现了这个问题，请问具体该怎么解决啊？
dashboard访问500，查看日志如下
```
from novaclient.v2 import security_group_rules as nova_rules
[Fri Feb 09 10:20:46.045811 2018] [:error] [pid 26780] [remote 172.16.11.62:36] ImportError: cannot import name security_group_rules
```

**Comment by WinstonZheng** [comment]
Horizon组件的依赖包有版本要求，nova-client的版本问题，最新版本将security_group_rules给弃用了。
在requirement.txt文件中有定义，查看一下当前novaclient版本，
```
//修改novaclient版本 
pip uninstall python-novaclient 
pip install python-novaclient==2.29.0
````
此外，有时候，同时，使用pip和apt安装了相同的依赖包，也会有冲突：
https://stackoverflow.com/questions/44356776/cant-launch-openstack-newton-horizon-dashboard-ioerrorremote-192-168-245-140

**Comment by heng-Yuan** [comment]
> 你好，我按照官网文档安装newton版本的dashboard也出现了这个问题，请问具体该怎么解决啊？
> dashboard访问500，查看日志如下
> 
> ```
> from novaclient.v2 import security_group_rules as nova_rules
> [Fri Feb 09 10:20:46.045811 2018] [:error] [pid 26780] [remote 172.16.11.62:36] ImportError: cannot import name security_group_rules
> ```
